"""Initial migration

Revision ID: 9e956878800c
Revises:
Create Date: 2025-06-12 12:20:46.437846+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e956878800c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "question", sa.String(length=100), nullable=False, comment="知识点"
        ),
        sa.Column(
            "answer", sa.String(length=500), nullable=False, comment="答案"
        ),
        sa.Column(
            "review_count", sa.Integer(), nullable=False, comment="复习次数"
        ),
        sa.Column(
            "next_review_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="下次复习时间",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    op.create_index(
        op.f("ix_cards_next_review_at"),
        "cards",
        ["next_review_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cards_question"), "cards", ["question"], unique=False
    )
    op.create_table(
        "review_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "review_count", sa.Integer(), nullable=False, comment="第几次复习"
        ),
        sa.Column(
            "interval_days",
            sa.Integer(),
            nullable=False,
            comment="复习间隔天数",
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="设置描述",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="是否启用",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_settings_id"), "review_settings", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_settings_id"), table_name="review_settings")
    op.drop_table("review_settings")
    op.drop_index(op.f("ix_cards_question"), table_name="cards")
    op.drop_index(op.f("ix_cards_next_review_at"), table_name="cards")
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.drop_table("cards")
    # ### end Alembic commands ###
