"""fix review_rules unique index to user_id+review_count (order fixed)

Revision ID: 08299a39220c
Revises: fe4147102fa0
Create Date: 2025-06-22 05:04:43.061736+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08299a39220c"
down_revision: Union[str, None] = "fe4147102fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_rules_review_count", table_name="review_rules")
    op.create_index(
        op.f("ix_review_rules_review_count"),
        "review_rules",
        ["review_count"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_review_count", "review_rules", ["user_id", "review_count"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_review_count", "review_rules", type_="unique")
    op.drop_index(
        op.f("ix_review_rules_review_count"), table_name="review_rules"
    )
    op.create_index(
        "ix_review_rules_review_count",
        "review_rules",
        ["review_count"],
        unique=False,
    )
    # ### end Alembic commands ###
