"""init

Revision ID: 21cb712b075d
Revises:
Create Date: 2025-06-18 12:12:16.866961+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "21cb712b075d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "users", sa.Column("email", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=100), nullable=False),
    )
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("is_superuser", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "users",
        "openid",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
        nullable=True,
        comment=None,
        existing_comment="微信openid",
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.drop_column("users", "nickname")
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=256),
            nullable=True,
            comment="微信头像url",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "nickname",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
            comment="微信昵称",
        ),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column(
        "users",
        "openid",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
        nullable=False,
        comment="微信openid",
    )
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "is_active")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
