"""update_user_model_add_nickname_avatar

Revision ID: 67ae83722009
Revises: 21cb712b075d
Create Date: 2025-06-21 09:41:41.629508+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "67ae83722009"
down_revision: Union[str, None] = "21cb712b075d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("nickname", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("avatar", sa.String(length=500), nullable=True)
    )
    op.alter_column(
        "users",
        "openid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=False,
    )
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "username",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=False,
        ),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.alter_column(
        "users",
        "openid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64
        ),
        nullable=True,
    )
    op.drop_column("users", "avatar")
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
